version: 0.2

phases:
  build:
    commands:
      - docker build -t web_app_aws .
      - docker tag web_app_aws:latest <account_id>.dkr.ecr.ap-south-1.amazonaws.com/web_app_aws:latest
      - docker push <account_id>.dkr.ecr.ap-south-1.amazonaws.com/web_app_aws:latest
